add_executable(test_declaration_lhs_parse test_declaration_lhs_parse.c)
target_link_libraries(test_declaration_lhs_parse ptx_parse ptx_print ptx_ast prelude)

add_executable(test_attribute_parse test_attribute_parse.c)
target_link_libraries(test_attribute_parse ptx_parse ptx_print ptx_ast prelude)

add_executable(test_declaration_with_attribute test_declaration_with_attribute.c)
target_link_libraries(test_declaration_with_attribute ptx_parse ptx_print ptx_ast prelude)

add_executable(test_function_parse test_function_parse.c)
target_link_libraries(test_function_parse ptx_parse ptx_print ptx_ast prelude)

add_executable(test_code_block_parse test_code_block_parse.c)
target_link_libraries(test_code_block_parse ptx_parse ptx_print ptx_ast prelude)

add_executable(test_function_with_body_parse test_function_with_body_parse.c)
target_link_libraries(test_function_with_body_parse ptx_parse ptx_print ptx_ast prelude)

add_executable(test_dynamic_kernel_parse test_dynamic_kernel_parse.c)
target_link_libraries(test_dynamic_kernel_parse ptx_parse ptx_print ptx_ast prelude) 